### ISSUE TITLE
artk version in utils is tagged at the wrong commit

### ISSUE THREAD

**Issue by Gloorf** [Semi-croustillants/S4A-Embedded#6]
ARTK in utils is tagged as f51791cd7be22efb455d2b44f26cf11844775bf0. This version is not updated and contains two bugs :
- ARTK_SetOptions takes int, int as param, where the transcribed code is only giving one parameter (one int)
- ARTK kernel looks for Setup() but transcribed code is writing Setup_ARTK()

Using latest ARTK version ( https://github.com/Semi-croustillants/artk/tree/artkforUnleashArduino) is working fine !

**Comment by AlexLamande** [comment]
Thx for this info, i'll fix that ASAP
:cookie:

**Comment by AlexLamande** [comment]
NAILED IT !
![easy one](https://media.giphy.com/media/y5yzypjVc9u3S/giphy.gif)
